export * as profile from './profile.service'
export * as gameInit from './game-init.service'
export * as setting from './settings.service'
export * as spin from './spin.service'
export * as symbol from './symbol.service'
export * as wallet from './wallet.service'
